all: igra uadb era5

igra:
  echo "Downloading Integrated Radiosonde Archive version 2"
  bash download_IGRA.sh
  
uadb:
  echo "Downloading Upper Air Database"
  csh download_UADB.csh

era5:
  echo "ERA5"
