subroutine identify_station(CD_CIDENT,CL_CSNO,P_RLAT,P_RLON,Z_PLAT,Z_PLON,JSGC,JEGC,I_NGP,I_NGC,I_KG,I_KM,I_KJ)

IMPLICIT NONE

!!     2.   DETERMINE TABLES AND TARGET

!!     2.1  DETECT THE STATION GROUP
INTEGER, PARAMETER :: JPRM=4
INTEGER, PARAMETER :: JPIM=4
INTEGER(KIND=JPIM)::I_NXGC      , I_NXGP      
PARAMETER (I_NXGC=15000, I_NXGP=3100)

REAL(KIND=JPRM)     , DIMENSION (I_NXGC) :: Z_PLAT,Z_PLON
CHARACTER(LEN= 6), DIMENSION (I_NXGC) :: CL_CSNG,CL_CSNO
CHARACTER(LEN= 6) :: CL_C1,CL_C4
CHARACTER(LEN= 1) :: CL_C0
CHARACTER(LEN= 5) :: CL_C2
CHARACTER(LEN=19) :: CL_C3
CHARACTER(LEN=5)  :: CD_CIDENT
INTEGER(KIND=JPIM)  , DIMENSION (I_NXGP) :: JSGC,JEGC,I_MREP
REAL(KIND=JPRM)     , DIMENSION (I_NXGP) :: Z_QLAT,Z_QLON
REAL(KIND=JPRM)     :: P_RLAT,P_RLON
INTEGER(KIND=JPIM) :: I_NGC,I_NGP,I_KM,I_KG,I,J,I_KJ
INTEGER(KIND=JPIM) :: IPLAT,IPLON,IRLAT,IRLON

I_KG = 0 ; I_KM = 0

DO I=1,I_NGP
  DO J=JSGC(I),JEGC(I)
    IPLAT = NINT(Z_PLAT(J)*100)
    IPLON = NINT(Z_PLON(J)*100)
    IRLAT = NINT(P_RLAT*100)
    IRLON = NINT(P_RLON*100)
    IF (IRLAT == IPLAT.AND.IRLON == IPLON) THEN
      IF (CD_CIDENT(1:5) == CL_CSNO(J)(1:5)) THEN
        I_KG = I               !! STATION GROUP
        I_KJ=  J
        I_KM = J-JSGC(I)+1     !! MEMBER 
        GOTO 440
      ENDIF
    ENDIF
  ENDDO
ENDDO
440 CONTINUE

IF (I_KG*I_KM == 0 .and. .false.) THEN
  WRITE(*,'(A,A6,F7.2,F8.2,I6,I3,2A)') &
   & 'BIASCOR: K_ID,LAT,LON,GRP,MEM= ',CD_CIDENT,P_RLAT,P_RLON,I_KG,I_KM, &
   & ' | THE SPECIFIED DATA WAS NOT FOUND ', &
   & 'IN THE STATION GROUP DEFINITION TABLE.'  
      !! THE SPECIFIED DATA WAS NOT FOUND IN THE STATION GROUP DEFINITION TABLE.
ENDIF

end subroutine identify_station


